### ISSUE TITLE
Server Side Rendering error

### ISSUE THREAD

**Issue by nyl-auster** [divyanshu013/react-animated-weather#4]
Hello ! thanks for this library, i love it ! I am using Next.js and this give me this error
```
ReferenceError: window is not defined
    at Object.<anonymous> (/.../node_modules/react-animated-weather/build/skycons.js:644:3)
```

**Comment by divyanshu013** [comment]
Hey @nyl-auster, thanks for opening an issue. I think this error is happening since node doesn't have a `window` object. I'll look more into this.

Will probably have to find a workaround for using canvas on node, maybe node-canvas. I'll post my findings here

**Comment by nyl-auster** [comment]
@divyanshu013 nice ! 
for now i just use this workaround at the end of skycons.js and it works fine with next.js
```
(typeof window !== undefined ? window : global)
```

**Comment by divyanshu013** [comment]
Did you get it working @nyl-auster ?

**Comment by nyl-auster** [comment]
@divyanshu013 not really, i just extracted your package , put them in my own components directory, and remove window from this line : https://github.com/nyl-auster/meteo-nantes/blob/master/components/ReactAnimatedWeather/skycons.js#L730

**Comment by nyl-auster** [comment]
@divyanshu013 PS : and it works : https://nantes-pluie.now.sh/

**Comment by divyanshu013** [comment]
Great @nyl-auster site looks nice! Also I've figured out a better check for `window` or `global`. Will update the library and release a newer version soon. BTW thanks for pointing out this issue with next.js :slightly_smiling_face:

**Comment by divyanshu013** [comment]
@nyl-auster just updated the lib to `v1.0.3`, should work fine with next.js now. Let me know if you see any problems after upgrading and thanks for creating this issue.

**Comment by nyl-auster** [comment]
@divyanshu013 yep it works perfectly fine, hurrah ! https://nantes-pluie.now.sh/
